num1=int(input("enter the First number"))
num2=int(input("enter the Second number"))
print("Addition:",num1+num2)
print("Subtraction:",num1-num2)
print("Multiplication:",num1*num2)
print("Divison:",num1/num2)